CREATE TABLE cleaning_tool_purchase_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL,
    cleaning_tool_id BIGINT,
    requested_by BIGINT NOT NULL,
    reviewed_by BIGINT,
    item_name VARCHAR(150) NOT NULL,
    quantity INTEGER NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    estimated_unit_price BIGINT,
    actual_unit_price BIGINT,
    rejection_reason TEXT,
    submitted_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    purchased_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,

    CONSTRAINT chk_cleaning_tool_purchase_requests_quantity CHECK ( quantity > 0 ),
    CONSTRAINT chk_cleaning_tool_purchase_requests_estimated_unit_price CHECK ( estimated_unit_price IS NULL OR estimated_unit_price >= 0 ),
    CONSTRAINT chk_cleaning_tool_purchase_requests_actual_unit_price CHECK ( actual_unit_price IS NULL OR actual_unit_price >= 0 ),
    CONSTRAINT chk_cleaning_tool_purchase_requests_status CHECK ( status IN ('draft','pending','approved','rejected','purchased','completed') ),

    CONSTRAINT fk_cleaning_tool_purchase_requests_office FOREIGN KEY (office_id) REFERENCES offices(id),
    CONSTRAINT fk_cleaning_tool_purchase_requests_cleaning_tool FOREIGN KEY (cleaning_tool_id) REFERENCES cleaning_tools(id),
    CONSTRAINT fk_cleaning_tool_purchase_requests_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cleaning_tool_purchase_requests_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX idx_cleaning_tool_purchase_requests_office_id_status ON cleaning_tool_purchase_requests(office_id,status);
CREATE INDEX idx_cleaning_tool_purchase_requests_requested_by ON cleaning_tool_purchase_requests(requested_by);
CREATE INDEX idx_cleaning_tool_purchase_requests_reviewed_by ON cleaning_tool_purchase_requests(reviewed_by);
CREATE INDEX idx_cleaning_tool_purchase_requests_created_at ON cleaning_tool_purchase_requests(created_at);