CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    office_id BIGINT NOT NULL,
    family_name VARCHAR(100) NOT NULL,
    given_name VARCHAR(100) NOT NULL,
    family_name_kana VARCHAR(100),
    given_name_kana VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    employment_start_date DATE,
    employment_end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_employees_uuid UNIQUE (uuid),
    CONSTRAINT fk_employees_office FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT
);