CREATE TABLE cleaning_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    minimum_quantity INTEGER,
    unit VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_cleaning_tools_office_code UNIQUE (office_id,code),
    CONSTRAINT chk_cleaning_tools_quantity CHECK ( quantity >= 0 ),
    CONSTRAINT chk_cleaning_tools_minimum_quantity CHECK ( minimum_quantity IS NULL OR minimum_quantity >= 0 ),
    CONSTRAINT fk_cleaning_tools_office FOREIGN KEY (office_id) REFERENCES offices(id)
);