CREATE TABLE notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    endpoint_url TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    notify_schedule_confirmed BOOLEAN NOT NULL DEFAULT TRUE,
    notify_purchase_submitted BOOLEAN NOT NULL DEFAULT TRUE,
    notify_purchase_approved BOOLEAN NOT NULL DEFAULT TRUE,
    notify_purchase_rejected BOOLEAN NOT NULL DEFAULT TRUE,
    notify_low_stock BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_notification_settings_office_provider UNIQUE (office_id,provider),
    CONSTRAINT fk_notification_settings_office FOREIGN KEY (office_id) REFERENCES offices(id)
);