CREATE TABLE cleaning_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_area_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_cleaning_tasks_office_area_code UNIQUE (office_area_id, code),
    CONSTRAINT fk_cleaning_tasks_office_area FOREIGN KEY (office_area_id) REFERENCES office_areas(id) ON DELETE RESTRICT
);