CREATE TABLE weekly_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cleaning_week_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    cleaning_task_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_weekly_assignments_cleaning_week_employee UNIQUE (cleaning_week_id, employee_id),
    CONSTRAINT uq_weekly_assignments_cleaning_week_cleaning_task UNIQUE (cleaning_week_id, cleaning_task_id),
    CONSTRAINT fk_weekly_assignments_cleaning_week FOREIGN KEY (cleaning_week_id) REFERENCES cleaning_weeks(id) ON DELETE RESTRICT,
    CONSTRAINT fk_weekly_assignments_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT,
    CONSTRAINT fk_weekly_assignments_cleaning_task FOREIGN KEY (cleaning_task_id) REFERENCES cleaning_tasks(id) ON DELETE RESTRICT
);

CREATE INDEX idx_weekly_assignments_employee_id ON weekly_assignments(employee_id);
CREATE INDEX idx_weekly_assignments_cleaning_task_id ON weekly_assignments(cleaning_task_id);