CREATE TABLE cleaning_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_by BIGINT,
    confirmed_by BIGINT,
    confirmed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,

    CONSTRAINT chk_cleaning_weeks_status CHECK ( status IN ('draft','confirmed','completed') ),
    CONSTRAINT chk_cleaning_weeks_date_range CHECK ( week_end_date = week_start_date + 6 ),
    CONSTRAINT chk_cleaning_weeks_start_monday CHECK ( EXTRACT(ISODOW FROM week_start_date) = 1 ),

    CONSTRAINT uq_cleaning_weeks_office_week_start_date UNIQUE (office_id, week_start_date),
    CONSTRAINT fk_cleaning_weeks_office FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cleaning_weeks_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cleaning_weeks_user FOREIGN KEY (confirmed_by) REFERENCES users(id) ON DELETE RESTRICT
);